# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ventana import *
from calendar import *
from tarifas import *
from PyQt5 import QtWidgets, QtCore
import sys, conexion, var, eventos, rutas
from datetime import datetime, date
import locale
locale.setlocale(locale.LC_ALL, 'esp')

class DialogCalendar(QtWidgets.QDialog):
    def __init__(self):
        super(DialogCalendar, self).__init__()
        var.dlgcalendar = Ui_dlgCalendar()
        var.dlgcalendar.setupUi(self)
        dia = datetime.now().day
        mes = datetime.now().month
        ano = datetime.now().year
        var.dlgcalendar.Calendar.setSelectedDate((QtCore.QDate(ano, mes, dia)))
        var.dlgcalendar.Calendar.clicked.connect(eventos.Eventos.cargaFecha)

class DialogTarifas(QtWidgets.QDialog):
    def __init__(self):
        super(DialogTarifas, self).__init__()
        var.dlgtarifas = Ui_dlgTarifas()
        var.dlgtarifas.setupUi(self)
        var.tarifas = [var.dlgtarifas.txtLoc, var.dlgtarifas.txtPro, var.dlgtarifas.txtReg,var.dlgtarifas.txtNac]
        var.dlgtarifas.btnActualiza.clicked.connect(conexion.Conexion.actualizaTarifas)


class Main(QtWidgets.QMainWindow):
    def __init__(self):
        '''
        Genera y conecta todos los eventos.
        '''
        super(Main,self).__init__()
        var.ui = Ui_MainWindow()
        var.ui.setupUi(self)

        ''' Instanciar ventanas auxiliares'''

        var.dlgcalendar = DialogCalendar()
        var.dlgtarifas = DialogTarifas()

        '''
        Conexión a la base de datos.
        Llenado de combos
        '''
        conexion.Conexion.db_connect(self)
        conexion.Conexion.listarFurgo(self)
        conexion.Conexion.listarCon(self)
        conexion.Conexion.cargarCmbM(var.ui.cmbMat)
        conexion.Conexion.cargarCmbC(var.ui.cmbCon)



        '''
        llamadas a los eventos de los botones
        '''
        var.ui.btnGrabar.clicked.connect(eventos.Eventos.cargaFurgo)
        var.ui.btnReload.clicked.connect(eventos.Eventos.limpiaFurgo)
        var.ui.btnEliminar.clicked.connect(eventos.Eventos.bajaFurgo)
        var.ui.btnModificar.clicked.connect(eventos.Eventos.modifFurgo)
        var.ui.btnAltacon.clicked.connect(eventos.Eventos.altaCon)
        var.ui.btnEliminacon.clicked.connect(eventos.Eventos.bajaCon)
        var.ui.btnModifcon.clicked.connect(eventos.Eventos.modifCon)
        var.ui.btnReloadcon.clicked.connect(eventos.Eventos.limpiaCon)
        var.ui.btnCalendar.clicked.connect(eventos.Eventos.abrirCalendar)
        var.ui.btnAltaruta.clicked.connect(rutas.Rutas.altaRuta)


        '''
        eventos cajas texto
        '''
        var.ui.txtMatricula.editingFinished.connect(eventos.Eventos.matCapital)
        var.ui.txtDni.editingFinished.connect(eventos.Eventos.validarDni)
        var.ui.txtDni.editingFinished.connect(eventos.Eventos.dniCapital)
        var.ui.txtNombre.editingFinished.connect(eventos.Eventos.nombreCapital)
        var.ui.txtKmf.editingFinished.connect(eventos.Eventos.calculaDistancia)
        '''
        eventos de las tablas
        '''
        var.ui.tabFurgo.clicked.connect(eventos.Eventos.datosUnoFurgo)
        var.ui.tabFurgo.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)
        var.ui.tabConductor.clicked.connect(eventos.Eventos.datosUnCon)
        var.ui.tabConductor.setSelectionBehavior(QtWidgets.QTableWidget.SelectRows)
        var.ui.tabFurgo.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        var.ui.tabConductor.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        '''
        eventos tarifas
        '''

        var.ui.btnTiporuta.buttonClicked.connect(eventos.Eventos.calculaTarifa)

        '''
        eventos menubar
        '''
        var.ui.menuBarSalir.triggered.connect(eventos.Eventos.Salir)
        var.ui.menuBarTarifas.triggered.connect(rutas.Rutas.mostrarTarifas)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    locale = QtCore.QLocale.system().name()
    qtTranslator = QtCore.QTranslator()
    app.installTranslator(qtTranslator)
    window = Main()
    window.setFixedSize(1024,768)
    window.show()
    sys.exit(app.exec())
