# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarifas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgTarifas(object):
    def setupUi(self, dlgTarifas):
        dlgTarifas.setObjectName("dlgTarifas")
        dlgTarifas.setWindowModality(QtCore.Qt.ApplicationModal)
        dlgTarifas.resize(400, 300)
        dlgTarifas.setModal(True)
        self.lblLocal = QtWidgets.QLabel(dlgTarifas)
        self.lblLocal.setGeometry(QtCore.QRect(60, 50, 56, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLocal.setFont(font)
        self.lblLocal.setObjectName("lblLocal")
        self.lblProvincia = QtWidgets.QLabel(dlgTarifas)
        self.lblProvincia.setGeometry(QtCore.QRect(60, 80, 56, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProvincia.setFont(font)
        self.lblProvincia.setObjectName("lblProvincia")
        self.lblRegional = QtWidgets.QLabel(dlgTarifas)
        self.lblRegional.setGeometry(QtCore.QRect(60, 110, 56, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblRegional.setFont(font)
        self.lblRegional.setObjectName("lblRegional")
        self.lblNacional = QtWidgets.QLabel(dlgTarifas)
        self.lblNacional.setGeometry(QtCore.QRect(60, 140, 56, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNacional.setFont(font)
        self.lblNacional.setObjectName("lblNacional")
        self.txtLoc = QtWidgets.QLineEdit(dlgTarifas)
        self.txtLoc.setGeometry(QtCore.QRect(130, 50, 125, 20))
        self.txtLoc.setMinimumSize(QtCore.QSize(120, 0))
        self.txtLoc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtLoc.setObjectName("txtLoc")
        self.txtPro = QtWidgets.QLineEdit(dlgTarifas)
        self.txtPro.setGeometry(QtCore.QRect(130, 80, 125, 20))
        self.txtPro.setMinimumSize(QtCore.QSize(120, 0))
        self.txtPro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPro.setObjectName("txtPro")
        self.txtNac = QtWidgets.QLineEdit(dlgTarifas)
        self.txtNac.setGeometry(QtCore.QRect(130, 140, 125, 20))
        self.txtNac.setMinimumSize(QtCore.QSize(120, 0))
        self.txtNac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNac.setObjectName("txtNac")
        self.txtReg = QtWidgets.QLineEdit(dlgTarifas)
        self.txtReg.setGeometry(QtCore.QRect(130, 110, 125, 20))
        self.txtReg.setMinimumSize(QtCore.QSize(120, 0))
        self.txtReg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtReg.setObjectName("txtReg")
        self.lblRutas = QtWidgets.QLabel(dlgTarifas)
        self.lblRutas.setGeometry(QtCore.QRect(110, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblRutas.setFont(font)
        self.lblRutas.setObjectName("lblRutas")
        self.btnActualiza = QtWidgets.QPushButton(dlgTarifas)
        self.btnActualiza.setGeometry(QtCore.QRect(150, 180, 78, 23))
        self.btnActualiza.setObjectName("btnActualiza")

        self.retranslateUi(dlgTarifas)
        QtCore.QMetaObject.connectSlotsByName(dlgTarifas)

    def retranslateUi(self, dlgTarifas):
        _translate = QtCore.QCoreApplication.translate
        dlgTarifas.setWindowTitle(_translate("dlgTarifas", "Dialog"))
        self.lblLocal.setText(_translate("dlgTarifas", "Local:"))
        self.lblProvincia.setText(_translate("dlgTarifas", "Provincial:"))
        self.lblRegional.setText(_translate("dlgTarifas", "Regional:"))
        self.lblNacional.setText(_translate("dlgTarifas", "Nacional:"))
        self.lblRutas.setText(_translate("dlgTarifas", "XESTOR TARIFAS"))
        self.btnActualiza.setText(_translate("dlgTarifas", "Actualizar"))
