# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarifas.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgTarifas(object):
    def setupUi(self, dlgTarifas):
        dlgTarifas.setObjectName("dlgTarifas")
        dlgTarifas.setWindowModality(QtCore.Qt.ApplicationModal)
        dlgTarifas.resize(350, 280)
        dlgTarifas.setModal(True)
        self.lblRutas = QtWidgets.QLabel(dlgTarifas)
        self.lblRutas.setGeometry(QtCore.QRect(130, 30, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblRutas.setFont(font)
        self.lblRutas.setObjectName("lblRutas")
        self.btnActualiza = QtWidgets.QPushButton(dlgTarifas)
        self.btnActualiza.setGeometry(QtCore.QRect(140, 190, 78, 23))
        self.btnActualiza.setObjectName("btnActualiza")
        self.widget = QtWidgets.QWidget(dlgTarifas)
        self.widget.setGeometry(QtCore.QRect(60, 60, 199, 100))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblLocal = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLocal.setFont(font)
        self.lblLocal.setObjectName("lblLocal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblLocal)
        self.txtLoc = QtWidgets.QLineEdit(self.widget)
        self.txtLoc.setMinimumSize(QtCore.QSize(120, 0))
        self.txtLoc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtLoc.setObjectName("txtLoc")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtLoc)
        self.lblProvincia = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProvincia.setFont(font)
        self.lblProvincia.setObjectName("lblProvincia")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblProvincia)
        self.txtPro = QtWidgets.QLineEdit(self.widget)
        self.txtPro.setMinimumSize(QtCore.QSize(120, 0))
        self.txtPro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtPro.setObjectName("txtPro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPro)
        self.lblRegional = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblRegional.setFont(font)
        self.lblRegional.setObjectName("lblRegional")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblRegional)
        self.txtReg = QtWidgets.QLineEdit(self.widget)
        self.txtReg.setMinimumSize(QtCore.QSize(120, 0))
        self.txtReg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtReg.setObjectName("txtReg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtReg)
        self.lblNacional = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNacional.setFont(font)
        self.lblNacional.setObjectName("lblNacional")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblNacional)
        self.txtNac = QtWidgets.QLineEdit(self.widget)
        self.txtNac.setMinimumSize(QtCore.QSize(120, 0))
        self.txtNac.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNac.setObjectName("txtNac")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtNac)

        self.retranslateUi(dlgTarifas)
        QtCore.QMetaObject.connectSlotsByName(dlgTarifas)

    def retranslateUi(self, dlgTarifas):
        _translate = QtCore.QCoreApplication.translate
        dlgTarifas.setWindowTitle(_translate("dlgTarifas", "Xestor Tarifas"))
        self.lblRutas.setText(_translate("dlgTarifas", "XESTOR TARIFAS"))
        self.btnActualiza.setText(_translate("dlgTarifas", "Actualizar"))
        self.lblLocal.setText(_translate("dlgTarifas", "Local:"))
        self.lblProvincia.setText(_translate("dlgTarifas", "Provincial:"))
        self.lblRegional.setText(_translate("dlgTarifas", "Regional:"))
        self.lblNacional.setText(_translate("dlgTarifas", "Nacional:"))
